(defvar pn-rev 0)
(defvar pn-count 0)
(defvar pn-rem 0)

; Рекурсивная печать числа (никаких циклов и багов с return!)
(defun print-num-rec (n)
  (if (> n 0)
      (print-num-rec (/ n 10))
      0)
  (if (> n 0)
      (out 1 (+ (mod n 10) 48))
      0)
)

(defun print-num (n)
  (if (= n 0)
      (out 1 48)
      (print-num-rec n)
  )
)

; Хвостовая рекурсия (аккумулятор передается через стек)
(defun fact (n acc)
  (if (= n 0)
      (return acc)
      (fact (- n 1) (* acc n)) ; Рекурсивный вызов
  )
)

(print "Factorial of 6 is: ")
(print-num (fact 6 1))
(print "\n")