(defun print-num-rec (n)
  (if (> n 0)
      (print-num-rec (/ n 10))
      0)
  (if (> n 0)
      (out 1 (+ (mod n 10) 48))
      0)
)

(defun print-num (n)
  (if (= n 0)
      (out 1 48)
      (print-num-rec n)
  )
)

(defun fact (n acc)
  (if (= n 0)
      (return acc)
      (fact (- n 1) (* acc n))
  )
)

(print-num (fact 6 1))